name: Sync changes

on:
  push:
    branches:
      - master

jobs:
  glitch:
    runs-on: ubuntu-latest
    steps:
      -
        name: Sync to Glitch project
        uses: kanadgupta/glitch-sync@master
        with:
          project-id: '${{ secrets.projectId }}'
          auth-token: '${{ secrets.authToken }}'

  gh-pages:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build & deploy to github
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch origin gh-pages 2> /dev/null || {
            git checkout --orphan gh-pages
            git rm -rf . > /dev/null
            git commit --allow-empty -m "initial commit"
            git checkout ${GITHUB_REF##*/}
          }

          make deploy ROOT=${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER/}
